# Scientific Computing Basics with PyTorch

This notebook introduces fundamental operations in scientific computing using Python and PyTorch.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Datacompintensive/WignerCamp2025/blob/master/Mathematics/ComputingExercises_solution.ipynb)

Topics covered:
- Dot product
- Vector-matrix multiplication
- Matrix-matrix multiplication
- Eigendecomposition (real symmetric matrices)
- Percentile calculation

In [26]:
import torch

## Dot Product
The dot product of vectors $\vec{a}, \vec{b} \in \mathbb{R}^n$ is defined as:

\begin{equation}
\vec{a} \cdot \vec{b} = \sum_{i=1}^n a_i b_i.
\end{equation}

In [27]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
dot_product = a @ b
dot_product

tensor(32.)

### Exercise
Compute the dot product of $[1, 0, -1]$ and $[2, 3, 4]$.

In [28]:
# Solution
x = torch.tensor([1.0, 0.0, -1.0])
y = torch.tensor([2.0, 3.0, 4.0])
result = x @ y
result

tensor(-2.)

## Vector-Matrix Multiplication
Given a matrix $M \in \mathbb{R}^{n \times m}$ and a vector $\vec{v} \in \mathbb{R}^m$:

\begin{equation}
M\vec{v} = \vec{w} \in \mathbb{R}^n.
\end{equation}

In [29]:
M = torch.tensor([[3.0, 4.0],
                  [6.0, 7.0],
                  [9.0, 10.0]])
v = torch.tensor([1.0, 2.0])
w = M @ v
w

tensor([11., 20., 29.])

### Exercise
Multiply matrix $\begin{bmatrix}1 & 0 \\ 0 & 1 \end{bmatrix}$ from the left with $[2, -1]$.

In [30]:
# Solution
M = torch.tensor([[1.0, 0.0],
                  [0.0, 1.0]])
v = torch.tensor([2.0, -1.0])
result = M @ v
result

tensor([ 2., -1.])

## Matrix-Matrix Multiplication
Given $A \in \mathbb{R}^{n \times m}$ and $B \in \mathbb{R}^{m \times k}$:

\begin{equation}
C = AB \in \mathbb{R}^{n \times k}.
\end{equation}

In [31]:
A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])
B = torch.tensor([[5.0, 6.0],
                  [7.0, 8.0]])
C = A @ B
C

tensor([[19., 22.],
        [43., 50.]])

### Exercise
Multiply $\begin{bmatrix}2 & 0 \\ 0 & 2\end{bmatrix}$ with itself.

In [32]:
# Solution
A = torch.tensor([[2.0, 0.0],
                  [0.0, 2.0]])
result = A @ A
result

tensor([[4., 0.],
        [0., 4.]])

## Eigendecomposition (Real Symmetric Matrices)
Given a real symmetric matrix $A$, there exists a matrix $Q$ of orthonormal eigenvectors and a diagonal matrix $\Lambda$ of eigenvalues such that:

\begin{equation}
A = Q \Lambda Q^T.
\end{equation}

In [33]:
A = torch.tensor([[2.0, 0.0],
                  [0.0, 3.0]])
eigenvalues, eigenvectors = torch.linalg.eigh(A)
display(eigenvalues, eigenvectors)
idx = 0
eigenvalues[idx], eigenvectors[:, idx]

tensor([2., 3.])

tensor([[1., 0.],
        [0., 1.]])

(tensor(2.), tensor([1., 0.]))

### Exercise
Find the smallest eigenvalue and its eigenvector of $\begin{bmatrix}4 & 1 \\ 1 & 3\end{bmatrix}$.

In [34]:
# Solution
A = torch.tensor([[4.0, 1.0],
                  [1.0, 3.0]])
eigenvalues, eigenvectors = torch.linalg.eigh(A)
eigenvalues[0], eigenvectors[:, 0]

(tensor(2.3820), tensor([ 0.5257, -0.8507]))

## Percentiles
The $q$-th percentile of a dataset $x_1, x_2, \dots, x_n$ is the value below which $q\%$ of the observations fall.

In code:

In [35]:
data = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
percentile_50 = torch.quantile(data, 0.5)
percentile_50

tensor(3.)

### Exercise
Calculate the 25th and 75th percentiles of $[10, 20, 30, 40, 50]$.

In [36]:
# Solution
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
torch.quantile(data, torch.tensor([0.25, 0.75]))

tensor([20., 40.])