<a target="_blank" href="https://colab.research.google.com/github/Datacompintensive/WignerCamp2025/blob/master/BasicProgramming/numpy_basics.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# NumPy Self-Learning Notebook
This notebook is designed to help you learn NumPy. It covers array creation, basic operations, and slicing of multi-dimensional arrays. Each section includes explanations, examples, and tasks with solutions.

## Introduction to NumPy
NumPy is a fundamental package for scientific computing with Python. It provides support for arrays, matrices, and many mathematical functions.

In [1]:
# Importing NumPy
import numpy as np

## Creating Arrays
NumPy arrays can be created in several ways: from lists, using functions like `arange`, `zeros`, `ones`, and `random`.

In [2]:
# Creating arrays from lists
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# Creating arrays using arange
arr2 = np.arange(10)
print(arr2)

# Creating arrays of zeros
arr3 = np.zeros((3, 3))
print(arr3)

# Creating arrays of ones
arr4 = np.ones((2, 4))
print(arr4)

# Creating random arrays
arr5 = np.random.rand(5)
print(arr5)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.28008116 0.52920952 0.95478584 0.24428098 0.36563668]


### Task 1
Create the following arrays:
1. An array from a list: `[10, 20, 30, 40]`
2. An array with values from 5 to 14
3. A 4x4 array of zeros
4. A 3x3 array of ones
5. An array of 6 random numbers

In [3]:
# Task 1 Solution
# 1. Array from a list

# 2. Array with values from 5 to 14

# 3. 4x4 array of zeros

# 4. 3x3 array of ones

# 5. Array of 6 random numbers

## Basic Operations
NumPy supports element-wise operations as well as matrix operations. Here are some examples.

In [4]:
# Element-wise operations
arr = np.array([1, 2, 3, 4])
print(arr + 10)  # Adding 10 to each element
print(arr * 2)   # Multiplying each element by 2

# Matrix operations
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat1, mat2))  # Matrix multiplication
print(mat1@mat2)

[11 12 13 14]
[2 4 6 8]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Task 2
Perform the following operations:
1. Add 5 to each element of an array: `[10, 20, 30, 40]`
2. Multiply each element of an array by 3: `[1, 2, 3, 4, 5]`
3. Perform matrix multiplication on two 2x2 matrices:
   `[[1, 2], [3, 4]]` and `[[2, 0], [1, 2]]`

In [5]:
# Task 2 Solution
# 1. Add 5 to each element

# 2. Multiply each element by 3

# 3. Matrix multiplication

## Slicing Multi-Dimensional Arrays
Slicing in multi-dimensional arrays is similar to slicing in one-dimensional arrays, but you need to specify a slice for each dimension.

In [6]:
# Creating a 3x3 array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

# Slicing the array
print(arr2d[0, 1:3])  # First row, second and third columns
print(arr2d[1:3, 0:2]) # Second and third rows, first and second columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 3]
[[4 5]
 [7 8]]


### Task 3
Given the following 4x4 array:
```
arr2d = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])
```
Perform the following slices:
1. Extract the first two rows and columns
2. Extract the last two rows and columns
3. Extract the middle 2x2 sub-array

In [7]:
# Task 3 Solution
arr2d = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 1. Extract the first two rows and columns

# 2. Extract the last two rows and columns

# 3. Extract the middle 2x2 sub-array

## Conclusion
This notebook provided an introduction to NumPy, covering array creation, basic operations, and slicing of multi-dimensional arrays. Practice these concepts to become more comfortable with NumPy.