<a target="_blank" href="https://colab.research.google.com/github/Datacompintensive/WignerCamp2025/blob/master/BasicProgramming/pytorch_basics_solutions.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# PyTorch Self-Learning Notebook
This notebook is designed to help you learn the basics of PyTorch's linear algebra capabilities. It covers operations on tensors, finding unique elements with counts, and eigenvalue decomposition on GPU. Each section includes explanations, examples, and tasks with solutions.

## Introduction to PyTorch
PyTorch is an open-source machine learning library based on the Torch library. It is widely used for applications such as natural language processing and deep learning. In this notebook, we will focus on its linear algebra capabilities.

In [1]:
# Importing PyTorch
import torch

## Operations on Tensors
Tensors are the fundamental data structures in PyTorch. They are similar to NumPy arrays but can also be used on GPUs.

In [2]:
# Creating tensors
tensor1 = torch.tensor([1, 2, 3, 4])
print(tensor1)

# Basic operations
tensor2 = torch.tensor([5, 6, 7, 8])
print(tensor1 + tensor2)  # Element-wise addition
print(tensor1 * tensor2)  # Element-wise multiplication

tensor([1, 2, 3, 4])
tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])


### Task 1
Create the following tensors and perform element-wise addition and multiplication:
1. `tensor3 = [10, 20, 30, 40]`
2. `tensor4 = [2, 4, 6, 8]`

In [3]:
# Task 1 Solution
tensor3 = torch.tensor([10, 20, 30, 40])
tensor4 = torch.tensor([2, 4, 6, 8])

print(tensor3 + tensor4)  # Element-wise addition
print(tensor3 * tensor4)  # Element-wise multiplication

tensor([12, 24, 36, 48])
tensor([ 20,  80, 180, 320])


## Finding Unique Elements with Counts
PyTorch provides a function to find unique elements and their counts in a tensor.

In [4]:
# Finding unique elements and counts
tensor5 = torch.tensor([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique_elements, counts = torch.unique(tensor5, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts:", counts)

Unique elements: tensor([1, 2, 3, 4])
Counts: tensor([1, 2, 3, 4])


### Task 2
Given the tensor `tensor6 = [1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5]`, find the unique elements and their counts.

In [5]:
# Task 2 Solution
tensor6 = torch.tensor([1, 1, 2, 3, 3, 3, 4, 4, 5, 5, 5, 5])
unique_elements, counts = torch.unique(tensor6, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts:", counts)

Unique elements: tensor([1, 2, 3, 4, 5])
Counts: tensor([2, 1, 3, 2, 4])


## Eigenvalue Decomposition on GPU
PyTorch can perform eigenvalue decomposition on both CPU and GPU. Here, we'll show how to perform it on GPU if available.

In [12]:
# Checking for GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# Creating a matrix and moving it to GPU
matrix = torch.tensor([[1.0, 2.0], [2.0, 3.0]], device=device)
print(matrix)

print()
# Performing eigenvalue decomposition
eigenvalues, eigenvectors = torch.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

print()
# Performing eigenvalue decomposition
eigenvalues, eigenvectors = torch.linalg.eigh(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

cuda
tensor([[1., 2.],
        [2., 3.]], device='cuda:0')

Eigenvalues: tensor([-0.2361+0.j,  4.2361+0.j], device='cuda:0')
Eigenvectors:
 tensor([[-0.8507+0.j, -0.5257+0.j],
        [ 0.5257+0.j, -0.8507+0.j]], device='cuda:0')

Eigenvalues: tensor([-0.2361,  4.2361], device='cuda:0')
Eigenvectors:
 tensor([[ 0.8507,  0.5257],
        [-0.5257,  0.8507]], device='cuda:0')


### Task 3
Create a 2x2 matrix `[[4.0, 1.0], [2.0, 3.0]]` and perform eigenvalue decomposition on GPU.

In [15]:
# Task 3 Solution
matrix_task = torch.tensor([[4.0, 1.0], [2.0, 3.0]], device=device)
eigenvalues_task, eigenvectors_task = torch.linalg.eigh(matrix_task)
print("Eigenvalues:", eigenvalues_task)
print("Eigenvectors:", eigenvectors_task)

Eigenvalues: tensor([1.4384, 5.5616], device='cuda:0')
Eigenvectors: tensor([[-0.6154,  0.7882],
        [ 0.7882,  0.6154]], device='cuda:0')


## Conclusion
This notebook provided an introduction to PyTorch's linear algebra capabilities, covering operations on tensors, finding unique elements with counts, and eigenvalue decomposition on GPU. Practice these concepts to become more comfortable with PyTorch.